### ISSUE TITLE
Create prototypes to demo buy flow

### ISSUE THREAD

**Issue by avimehta** [subscriptions-project/swg-js#7]
Creating a tracking bug to track progress on demo flows. Let me know if we need to add more things to this list.

The primary task for this demo is to create  a flow that goes as follows:

Abbrv. Article -> Auth -> Offers -> Payments flow -> Full Article

runtime-tasks:
- [x] **Dima**: Binary for publishers to put on their site. #1
- [x] **Avi**: A fake server for subscription-platform responses. #8
- [x] **Dima**: Payment call #11
- [x] **Avi**: Abbrv. and full article support in test server
- [x] **Avi**: Multiple SP requests
- [ ] APIs to get runtime status, intercept different stages
- [ ] Already subscribed flow
- [ ] Have subscriptions flow
- [ ] Add JWT to the flow

UX tasks:
- [x] **Dipak**: Basic UI for offers (iframe?) 
- [x] **Dipak**: UI customization
- [x] **Dipak**: Metering UI toast

/cc @dparikh, @dvoytenko Please add more tasks
